### ISSUE TITLE
path has no method `isAbsolute`

### ISSUE THREAD

**Issue by perry-mitchell** [getify/ScanTree#4]
Trying to get a basic list of files:

```
scantree.scan({
  dirs: 'tmp/',
  base_dir: 'tmp/',
  recursive: true,
  groups: false,
  full_paths: true,
  output: 'simple' 
})
```

Which throws an ugly type error:

```
$ node test.js 

.../scantree/lib/index.js:77
        path.isAbsolute(pathStr)
             ^
TypeError: Object #<Object> has no method 'isAbsolute'
    at fixPath (.../scantree/lib/index.js:77:8)
    at Array.map (native)
    at processDirsOption (.../scantree/lib/index.js:341:4)
    at processOptions (.../scantree/lib/index.js:244:3)
    at Object.scan (.../scantree/lib/index.js:520:2)
    at Object.<anonymous> (.../test.js:3:22)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

Using scantree@0.4.0-a. `tmp/` is a directory beside my test.js script that has for js files with headers like `// require: d.js`. It occurs on 0.3.0-a as well, so I can't figure out what I'm doing...

```
$ node -v; npm -v
v0.10.29
2.1.10
```

**Comment by perry-mitchell** [comment]
Nvm, just a node version issue. Path needs > 0.10 for isAbsolute.
